/* warung.h generated by valac 0.22.0, the Vala compiler, do not modify */


#ifndef ____VAPI_WARUNG_H__
#define ____VAPI_WARUNG_H__

#include <glib.h>
#include <webkit/webkit.h>
#include <glib-object.h>
#include <JavaScriptCore/JavaScript.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define WARUNG_TYPE_MAIN (warung_main_get_type ())
#define WARUNG_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WARUNG_TYPE_MAIN, WarungMain))
#define WARUNG_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WARUNG_TYPE_MAIN, WarungMainClass))
#define WARUNG_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WARUNG_TYPE_MAIN))
#define WARUNG_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WARUNG_TYPE_MAIN))
#define WARUNG_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WARUNG_TYPE_MAIN, WarungMainClass))

typedef struct _WarungMain WarungMain;
typedef struct _WarungMainClass WarungMainClass;
typedef struct _WarungMainPrivate WarungMainPrivate;

#define WARUNG_TYPE_APP (warung_app_get_type ())
#define WARUNG_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WARUNG_TYPE_APP, WarungApp))
#define WARUNG_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WARUNG_TYPE_APP, WarungAppClass))
#define WARUNG_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WARUNG_TYPE_APP))
#define WARUNG_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WARUNG_TYPE_APP))
#define WARUNG_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WARUNG_TYPE_APP, WarungAppClass))

typedef struct _WarungApp WarungApp;
typedef struct _WarungAppClass WarungAppClass;
typedef struct _WarungAppPrivate WarungAppPrivate;

struct _WarungMain {
	WebKitWebView parent_instance;
	WarungMainPrivate * priv;
};

struct _WarungMainClass {
	WebKitWebViewClass parent_class;
};

struct _WarungApp {
	GObject parent_instance;
	WarungAppPrivate * priv;
};

struct _WarungAppClass {
	GObjectClass parent_class;
};


GType warung_main_get_type (void) G_GNUC_CONST;
WarungMain* warung_main_new (void);
WarungMain* warung_main_construct (GType object_type);
void* warung_main_get_context (WarungMain* self);
void warung_main_set_context (WarungMain* self, void* value);
GType warung_app_get_type (void) G_GNUC_CONST;
void* warung_app_injekrepo (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_updaterepo (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_upgradesistem (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_install0 (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void* warung_app_install1 (void* ctx, void* function, void* thisObject, void** arguments, int arguments_length1, void** exception);
void warung_app_setup_js_class (WarungApp* self, void* context);
WarungApp* warung_app_new (void);
WarungApp* warung_app_construct (GType object_type);
gchar* warung_util_string_from_js_string (void* s);
gchar* warung_util_string_property_from_value (void* ctx, void* val, const gchar* property_name);
void warung_util_evaluate_callback (void* ctx, const gchar* callback, const gchar* args);


G_END_DECLS

#endif
